### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [larobitrumpet/allegro-ui#1]
Hi. What license applies to your Allegro UI library? The same or similar as Allegro (zlib license)?

**Comment by larobitrumpet** [comment]
MIT license. I'll go ahead and add a license.

**Comment by LifeCANvs** [comment]
> MIT license. I'll go ahead and add a license.

Thank you so much for your kindness in allowing me and others to make use of your code with such a permissive license, and to learn from it without restrictions. When I eventually manage to create any worthwhile software/games with it (I am still very inexperienced at programming in C/C++), I will be sure to credit you for this library, and also to "pay it forward" by sharing back to you and others. Hopefully my programming skills can develop enough to allow me to build on your library and possibly add more functionality/features that could be useful :-) I see now that you also have a few C code games in your GH repository and they also have the same permissive license, so I will certainly take a look at those and try to learn more from you, as I take the next steps in my programming journey.

**Comment by larobitrumpet** [comment]
There are better Allegro UI libraries out there, such as this one: [https://github.com/SiegeLord/WidgetZ](https://github.com/SiegeLord/WidgetZ). If you want to play around with my little thing, go ahead, I won't stop you, but it is no where near production ready, there's barely anything. I have written no documentation, not even a README. Also know that I am not actively working on this project and I do not plan to add any more. Right now I'm working on basically a Rust version of this, and maybe I'll put that on GitHub in the near-ish future, probably sometime in the new year, we'll see. Good luck with whatever you decide to do!

**Comment by LifeCANvs** [comment]
> There are better Allegro UI libraries out there, such as this one: https://github.com/SiegeLord/WidgetZ. If you want to play around with my little thing, go ahead, I won't stop you, but it is no where near production ready, there's barely anything. I have written no documentation, not even a README. Also know that I am not actively working on this project and I do not plan to add any more. Right now I'm working on basically a Rust version of this, and maybe I'll put that on GitHub in the near-ish future, probably sometime in the new year, we'll see. Good luck with whatever you decide to do!

Thanks for your feedback and advice (and the link to to the WidgetZ Allegro library). Good luck with your Rust project. I will watch out for it.

**Comment by larobitrumpet** [comment]
Thank you! I might come back and work on this actually. We'll see.
